import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ChevronDownIcon, UploadCloudIcon } from 'lucide-react';
import { ModuleHeader, Panel } from '../../components/admin/Panel';
import { usePlatform } from '../../contexts/PlatformContext';
import { portalCompanyId, requirementsByCompany } from '../../data/companies';
import { requirementStatusMeta, StatusBadge } from '../../components/ui/StatusBadge';
import { DURATION, EASE_EMPHASIS } from '../../utils/motion';
const kindLabels: Record<string, string> = {
  archivo: 'Subir archivo',
  formulario: 'Completar formulario',
  firma: 'Firmar documento',
  pago: 'Registrar pago',
  confirmacion: 'Confirmar',
  listado: 'Cargar listado'
};
export function PortalRequirements() {
  const {
    session
  } = usePlatform();
  const companyId = session?.companyId ?? portalCompanyId;
  const list = requirementsByCompany(companyId);
  const [openId, setOpenId] = useState<string | null>(list[0]?.id ?? null);
  return <>
      <ModuleHeader eyebrow="Portal" title="Requerimientos" description="Todo lo que necesitamos de tu lado, con fecha límite y estado. Al resolver uno, el equipo lo revisa y te confirma." />

      <Panel emphasis title={`${list.length} requerimientos`}>
        <ul className="divide-y divide-line">
          {list.map((requirement) => {
          const meta = requirementStatusMeta[requirement.status];
          const isOpen = openId === requirement.id;
          return <li key={requirement.id}>
                <button type="button" onClick={() => setOpenId(isOpen ? null : requirement.id)} aria-expanded={isOpen} className="flex w-full items-center gap-3 px-5 py-4 text-left transition-colors duration-150 ease-emphasis hover:bg-canvas">
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-brand">{requirement.title}</p>
                    <p className="text-xs text-ink-muted">
                      {kindLabels[requirement.kind]} · vence {requirement.dueDate}
                      {requirement.autoGenerated ? ' · generado automáticamente' : ''}
                    </p>
                  </div>
                  <StatusBadge label={meta.label} tone={meta.tone} />
                  <ChevronDownIcon size={16} className={`shrink-0 text-ink-muted transition-transform duration-200 ease-emphasis ${isOpen ? 'rotate-180' : ''}`} />
                </button>

                <AnimatePresence initial={false}>
                  {isOpen ? <motion.div initial={{
                height: 0,
                opacity: 0
              }} animate={{
                height: 'auto',
                opacity: 1
              }} exit={{
                height: 0,
                opacity: 0
              }} transition={{
                duration: DURATION.panel,
                ease: EASE_EMPHASIS
              }} className="overflow-hidden bg-canvas">
                      <div className="px-5 py-5">
                        <p className="max-w-2xl text-sm leading-relaxed text-ink">
                          {requirement.description}
                        </p>

                        {requirement.kind === 'archivo' ? <div className="mt-5 flex flex-wrap items-center gap-3 rounded-xl border border-dashed border-line bg-white px-5 py-6">
                            <UploadCloudIcon size={22} className="text-brand-support" />
                            <div className="min-w-[200px] flex-1">
                              <p className="text-sm font-medium text-brand">
                                Arrastra el archivo o selecciónalo
                              </p>
                              <p className="text-xs text-ink-muted">
                                Formatos aceptados: SVG, PNG, PDF · máx. 10 MB
                              </p>
                            </div>
                            <button type="button" className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white transition-colors duration-200 ease-emphasis hover:bg-brand-deep">
                              Seleccionar archivo
                            </button>
                          </div> : <div className="mt-5 flex flex-wrap gap-3">
                            <button type="button" className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white transition-colors duration-200 ease-emphasis hover:bg-brand-deep">
                              {kindLabels[requirement.kind]}
                            </button>
                            <button type="button" className="rounded-lg border border-line bg-white px-4 py-2 text-sm font-semibold text-brand transition-colors duration-150 ease-emphasis hover:border-brand/40">
                              Tengo una duda
                            </button>
                          </div>}

                        {requirement.comments.length > 0 ? <ul className="mt-6 space-y-3 border-t border-line pt-5">
                            {requirement.comments.map((comment) => <li key={comment.id}>
                                <p className="text-xs font-semibold text-brand">
                                  {comment.author}{' '}
                                  <span className="font-normal text-ink-muted">{comment.date}</span>
                                </p>
                                <p className="mt-0.5 text-sm text-ink">{comment.text}</p>
                              </li>)}
                          </ul> : null}
                      </div>
                    </motion.div> : null}
                </AnimatePresence>
              </li>;
        })}
        </ul>
      </Panel>
    </>;
}