import type { SponsorTierId } from './commerce';

export type CompanyRole =
'patrocinador' |
'expositor' |
'aliado-comercial' |
'marca' |
'sociedad-medica' |
'aliado-academico' |
'aliado-institucional' |
'certificador' |
'organizador' |
'media-partner';

export type ParticipationStatus =
'en-negociacion' |
'aprobado' |
'publicado' |
'cerrado' |
'cancelado';

export interface Company {
  id: string;
  tradeName: string;
  legalName: string;
  nit: string;
  address: string;
  city: string;
  country: string;
  web: string;
  instagram: string;
  contactName: string;
  contactEmail: string;
  contactWhatsapp: string;
  description: string;
  /** Datos de muestra hasta que la empresa complete su perfil. */
  isSampleData: boolean;
  logoReady: boolean;
  /** Logotipo cuadrado 1:1 cargado por la marca en su Portal. */
  logoUrl?: string;
  brandAssets: BrandAsset[];
}

export type BrandAssetKind =
'logo-png' |
'logo-svg' |
'manual' |
'fotografia' |
'video' |
'producto' |
'publicidad';

export interface BrandAsset {
  id: string;
  companyId: string;
  kind: BrandAssetKind;
  name: string;
  status: 'pendiente' | 'cargado' | 'aprobado' | 'requiere-cambios';
  updatedAt: string;
}

/** Una empresa participa N veces; la empresa nunca se duplica por evento. */
export interface Participation {
  id: string;
  companyId: string;
  editionId: string;
  roles: CompanyRole[];
  packageTier?: SponsorTierId;
  packageName: string;
  standId?: string;
  includedTickets: number;
  activations: string[];
  sponsoredSpeakerTrackId?: string;
  trackId?: string;
  agreedAmount: number | null;
  paidAmount: number;
  status: ParticipationStatus;
  bannerTier?: 'principal' | 'destacado' | 'apoyo';
}

export type RequirementStatus =
'pendiente' |
'en-proceso' |
'en-revision' |
'requiere-cambios' |
'aprobado' |
'completado';

export type RequirementKind =
'archivo' |
'formulario' |
'firma' |
'pago' |
'confirmacion' |
'listado';

export interface Requirement {
  id: string;
  companyId: string;
  editionId: string;
  title: string;
  description: string;
  owner: string;
  dueDate: string;
  kind: RequirementKind;
  status: RequirementStatus;
  /** Generado por el sistema (p.ej. logo faltante para el banner). */
  autoGenerated: boolean;
  comments: RequirementComment[];
}

export interface RequirementComment {
  id: string;
  author: string;
  date: string;
  text: string;
}

export type CompanyDocumentKind =
'propuesta' |
'contrato' |
'orden' |
'certificado' |
'factura' |
'fiscal' |
'manual' |
'acuerdo' |
'otro';

export interface CompanyDocument {
  id: string;
  companyId: string;
  editionId: string;
  kind: CompanyDocumentKind;
  name: string;
  status: 'pendiente' | 'enviado' | 'firma-solicitada' | 'firmado' | 'aprobado';
  date: string;
  sizeLabel: string;
}

export interface CompanyPayment {
  id: string;
  companyId: string;
  editionId: string;
  concept: string;
  amount: number;
  dueDate: string;
  status: 'pendiente' | 'pagado' | 'vencido';
  paidAt?: string;
}

export interface ActivityEntry {
  id: string;
  companyId: string;
  editionId: string;
  date: string;
  actor: string;
  action: string;
  comment: string;
}