// =========================================================
// NOVO ARCHITECTURE — Mock data
// Datos realistas para desarrollo sin Supabase conectado.
// Swap por llamadas reales cuando se apliquen las migraciones.
// =========================================================

import type {
  NovoEvent, CommercialAgreement, EventRegistration,
  DashboardStats, EventKpis, Person,
} from '../../types/novo';

export const MOCK_EVENTS: NovoEvent[] = [
  {
    id: 'evt-eterna-primavera-2025',
    name: 'La Eterna Primavera',
    slug: 'eterna-primavera-2025',
    event_type: 'congreso',
    modality: 'presencial',
    audience: 'profesionales',
    start_date: '2025-11-14',
    end_date: '2025-11-15',
    start_time: '08:00',
    end_time: '18:00',
    timezone: 'America/Bogota',
    venue_name: 'Centro de Convenciones Medellín',
    venue_city: 'Medellín',
    venue_country: 'Colombia',
    is_public: true,
    is_free: false,
    cover_image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    description: 'Congreso nacional de medicina integrativa y salud preventiva.',
    tagline: 'Donde la ciencia y el bienestar se encuentran.',
    has_certificate: true,
    max_capacity: 400,
    is_featured: true,
    goals: { registros: 400, ingresos: 120000000 },
    operational_status: 'proximo',
    publication_status: 'publicado',
    created_at: '2025-06-01T10:00:00Z',
    updated_at: '2025-09-01T14:30:00Z',
    registrations_count: 312,
    revenue: 89400000,
  },
  {
    id: 'evt-hormobiota-vi-2025',
    name: 'Hormobiota VI',
    slug: 'hormobiota-vi-2025',
    event_type: 'congreso',
    modality: 'hibrido',
    audience: 'profesionales',
    start_date: '2025-10-03',
    end_date: '2025-10-04',
    start_time: '07:30',
    end_time: '17:00',
    timezone: 'America/Bogota',
    venue_name: 'Hotel Dann Carlton',
    venue_city: 'Bogotá',
    venue_country: 'Colombia',
    platform_name: 'Zoom Webinar',
    is_public: true,
    is_free: false,
    cover_image_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800',
    description: 'Congreso internacional de hormona y microbiota.',
    tagline: 'El eje que lo conecta todo.',
    has_certificate: true,
    max_capacity: 600,
    is_featured: false,
    goals: { registros: 600, ingresos: 200000000 },
    operational_status: 'activo',
    publication_status: 'publicado',
    created_at: '2025-03-15T09:00:00Z',
    updated_at: '2025-10-01T08:00:00Z',
    registrations_count: 581,
    revenue: 196800000,
  },
  {
    id: 'evt-masterclass-microbiota-q4',
    name: 'Masterclass Microbiota Clínica',
    slug: 'masterclass-microbiota-q4-2025',
    event_type: 'masterclass',
    modality: 'virtual',
    audience: 'profesionales',
    start_date: '2025-12-06',
    end_date: '2025-12-06',
    start_time: '09:00',
    end_time: '13:00',
    timezone: 'America/Bogota',
    platform_name: 'Zoom',
    is_public: true,
    is_free: false,
    cover_image_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800',
    description: 'Masterclass intensiva sobre aplicación clínica del microbioma.',
    has_certificate: true,
    max_capacity: 200,
    is_featured: false,
    goals: { registros: 200, ingresos: 30000000 },
    operational_status: 'proximo',
    publication_status: 'publicado',
    created_at: '2025-09-10T11:00:00Z',
    updated_at: '2025-09-10T11:00:00Z',
    registrations_count: 87,
    revenue: 13050000,
  },
  {
    id: 'evt-congreso-dolor-2026',
    name: 'Congreso Nacional del Dolor',
    slug: 'congreso-dolor-2026',
    event_type: 'congreso',
    modality: 'presencial',
    audience: 'profesionales',
    start_date: '2026-03-20',
    end_date: '2026-03-22',
    timezone: 'America/Bogota',
    venue_city: 'Cali',
    venue_country: 'Colombia',
    is_public: true,
    is_free: false,
    has_certificate: true,
    max_capacity: 500,
    is_featured: false,
    operational_status: 'borrador',
    publication_status: 'borrador',
    created_at: '2025-09-02T10:00:00Z',
    updated_at: '2025-09-02T10:00:00Z',
    registrations_count: 0,
    revenue: 0,
  },
  {
    id: 'evt-webinar-vitamina-d',
    name: 'Webinar Vitamina D: Más Allá del Hueso',
    slug: 'webinar-vitamina-d-2025',
    event_type: 'webinar',
    modality: 'virtual',
    audience: 'profesionales',
    start_date: '2025-09-25',
    end_date: '2025-09-25',
    start_time: '19:00',
    end_time: '21:00',
    timezone: 'America/Bogota',
    platform_name: 'Zoom',
    is_public: true,
    is_free: true,
    has_certificate: false,
    max_capacity: 1000,
    is_featured: false,
    goals: { registros: 1000 },
    operational_status: 'finalizado',
    publication_status: 'oculto',
    created_at: '2025-08-01T10:00:00Z',
    updated_at: '2025-09-26T00:00:00Z',
    registrations_count: 734,
    revenue: 0,
  },
];

export const MOCK_STATS: DashboardStats = {
  total_events: 5,
  active_events: 1,
  upcoming_events: 3,
  total_registrations: 1714,
  total_revenue: 299250000,
  total_companies: 38,
};

export const MOCK_KPIS: EventKpis = {
  event_id: 'evt-eterna-primavera-2025',
  registrations: 312,
  registrations_goal: 400,
  revenue: 89400000,
  revenue_goal: 120000000,
  sponsorships: 14,
  stands_sold: 9,
  stands_total: 12,
  checkins: 0,
  pending_alerts: 3,
};

export const MOCK_AGREEMENTS: CommercialAgreement[] = [
  {
    id: 'agr-001',
    company_id: 'co-001',
    event_id: 'evt-eterna-primavera-2025',
    origin: 'evento',
    status: 'cerrado',
    total: 18000000,
    currency: 'COP',
    current_version: 1,
    closed_at: '2025-07-14T16:00:00Z',
    created_at: '2025-07-01T09:00:00Z',
    updated_at: '2025-07-14T16:00:00Z',
    company: { id: 'co-001', name: 'Laboratorios Roche Colombia' },
    event: { id: 'evt-eterna-primavera-2025', name: 'La Eterna Primavera', slug: 'eterna-primavera-2025' },
  },
  {
    id: 'agr-002',
    company_id: 'co-002',
    event_id: 'evt-eterna-primavera-2025',
    origin: 'evento',
    status: 'aprobado',
    total: 8500000,
    currency: 'COP',
    current_version: 1,
    created_at: '2025-08-10T10:00:00Z',
    updated_at: '2025-09-01T11:00:00Z',
    company: { id: 'co-002', name: 'Nestlé Health Science' },
    event: { id: 'evt-eterna-primavera-2025', name: 'La Eterna Primavera', slug: 'eterna-primavera-2025' },
  },
];

export const MOCK_RECENT_REGISTRATIONS: EventRegistration[] = [
  {
    id: 'reg-001',
    person_id: 'p-001',
    event_id: 'evt-eterna-primavera-2025',
    registration_type: 'compra',
    origin: 'web',
    amount_paid: 480000,
    attended: false,
    created_at: '2025-09-02T08:30:00Z',
    updated_at: '2025-09-02T08:30:00Z',
    person: { id: 'p-001', full_name: 'Dra. Valentina Ospina', avatar_url: undefined },
    event: { id: 'evt-eterna-primavera-2025', name: 'La Eterna Primavera', slug: 'eterna-primavera-2025' },
  },
  {
    id: 'reg-002',
    person_id: 'p-002',
    event_id: 'evt-hormobiota-vi-2025',
    registration_type: 'sponsor',
    origin: 'portal-empresa',
    company_id: 'co-001',
    amount_paid: 0,
    attended: true,
    created_at: '2025-09-01T17:00:00Z',
    updated_at: '2025-09-01T17:00:00Z',
    person: { id: 'p-002', full_name: 'Juan Pablo Restrepo', avatar_url: undefined },
    event: { id: 'evt-hormobiota-vi-2025', name: 'Hormobiota VI', slug: 'hormobiota-vi-2025' },
  },
  {
    id: 'reg-003',
    person_id: 'p-003',
    event_id: 'evt-masterclass-microbiota-q4',
    registration_type: 'compra',
    origin: 'web',
    amount_paid: 150000,
    attended: false,
    created_at: '2025-09-01T14:20:00Z',
    updated_at: '2025-09-01T14:20:00Z',
    person: { id: 'p-003', full_name: 'Dr. Andrés Morales', avatar_url: undefined },
    event: { id: 'evt-masterclass-microbiota-q4', name: 'Masterclass Microbiota Clínica', slug: 'masterclass-microbiota-q4-2025' },
  },
];

export const MOCK_ALERTS = [
  { id: 'a1', level: 'alta' as const, message: 'La Eterna Primavera: 88 cupos restantes — meta a 78%', link: '/novo/eventos/evt-eterna-primavera-2025', event: 'La Eterna Primavera' },
  { id: 'a2', level: 'alta' as const, message: '2 acuerdos pendientes de aprobación', link: '/novo/empresas', event: undefined },
  { id: 'a3', level: 'media' as const, message: 'Nestlé Health Science: cuota del 50% vence en 8 días', link: '/novo/empresas', event: 'La Eterna Primavera' },
  { id: 'a4', level: 'baja' as const, message: 'Masterclass Microbiota: foto de portada pendiente', link: '/novo/eventos/evt-masterclass-microbiota-q4', event: 'Masterclass Microbiota' },
];
