import React from 'react';
import { FileTextIcon } from 'lucide-react';
import { ModuleHeader, Panel, tdClass, thClass } from '../../components/admin/Panel';
import { usePlatform } from '../../contexts/PlatformContext';
import { companies, companyDocuments, getCompany, requirements } from '../../data/companies';
import { requirementStatusMeta, StatusBadge } from '../../components/ui/StatusBadge';
export function DocumentsAdmin() {
  const {
    activeEditionId
  } = usePlatform();
  const documents = companyDocuments.filter((document) => document.editionId === activeEditionId);
  const open = requirements.filter((item) => item.editionId === activeEditionId && item.status !== 'completado' && item.status !== 'aprobado');
  const missingLogos = companies.filter((company) => !company.logoReady);
  return <>
      <ModuleHeader eyebrow="Comercial" title="Documentos y requerimientos" description="Repositorio por empresa y lista de lo que falta. La firma electrónica queda en estado solicitada." />

      <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]">
        <Panel emphasis title={`${documents.length} documentos`}>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px]">
              <thead className="bg-canvas">
                <tr>
                  <th className={thClass}>Documento</th>
                  <th className={thClass}>Empresa</th>
                  <th className={thClass}>Tipo</th>
                  <th className={thClass}>Fecha</th>
                  <th className={thClass}>Estado</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-line">
                {documents.map((document) => <tr key={document.id} className="transition-colors duration-150 hover:bg-canvas">
                    <td className={`${tdClass} font-medium text-brand`}>
                      <span className="inline-flex items-center gap-2">
                        <FileTextIcon size={15} className="text-ink-muted" />
                        {document.name}
                      </span>
                    </td>
                    <td className={tdClass}>{getCompany(document.companyId)?.tradeName}</td>
                    <td className={`${tdClass} capitalize`}>{document.kind}</td>
                    <td className={tdClass}>{document.date}</td>
                    <td className={tdClass}>
                      <StatusBadge label={document.status} tone={document.status === 'firma-solicitada' ? 'warning' : 'info'} />
                    </td>
                  </tr>)}
              </tbody>
            </table>
          </div>
        </Panel>

        <div className="space-y-5">
          <Panel title={`${open.length} requerimientos abiertos`}>
            <ul className="divide-y divide-line">
              {open.map((item) => <li key={item.id} className="px-5 py-3">
                  <div className="flex items-start gap-3">
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-brand">{item.title}</p>
                      <p className="text-xs text-ink-muted">
                        {item.owner} · vence {item.dueDate}
                      </p>
                    </div>
                    <StatusBadge label={requirementStatusMeta[item.status].label} tone={requirementStatusMeta[item.status].tone} />
                  </div>
                  {item.autoGenerated ? <p className="mt-1 text-xs text-amber-700">Generado automáticamente</p> : null}
                </li>)}
            </ul>
          </Panel>

          <Panel title="Logos faltantes para el banner">
            <ul className="divide-y divide-line">
              {missingLogos.length === 0 ? <li className="px-5 py-4 text-sm text-ink-muted">Todas las marcas tienen logo listo.</li> : missingLogos.map((company) => <li key={company.id} className="flex items-center justify-between gap-3 px-5 py-3">
                    <span className="text-sm font-medium text-brand">{company.tradeName}</span>
                    <StatusBadge label="Falta SVG" tone="danger" />
                  </li>)}
            </ul>
          </Panel>
        </div>
      </div>
    </>;
}